train_file: ['/projects/nlp/data/data/multimodal-gender-bias/data/ALBEF/mscoco/annotations/coco_train.hendrix.json']
train_neutral_file: ['/projects/nlp/data/data/multimodal-gender-bias/data/ALBEF/mscoco/gender-neutral/coco_train.hendrix.json']
bert_config: 'configs/config_bert.json'

image_res: 256
vision_width: 768

embed_dim: 256

batch_size: 64
temp: 0.07
mlm_probability: 0.15
max_words: 30

p_neutral_caption: 0.15
neutral_epochs: 1

distill: True
queue_size: 65536
momentum: 0.995
alpha: 0.4

optimizer: {opt: adamW, lr: 5e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 5e-5, epochs: 1, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 0.1, cooldown_epochs: 0}
