TASK1:
  name: VQA
  type: VL-classifier
  num_labels: 3129
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: /projects/nlp_mgr-AUDIT/data/dataset/sxk199/vqa
  features_h5path1: /projects/nlp_mgr-AUDIT/data/dataset/sxk199/mscoco/resnet101_faster_rcnn_genome_imgfeats/finetuning/trainval_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00005
  num_epoch: 10
  format: 'lmdb'
TASK8:
  name: RetrievalFlickr30k
  type: VL-logit
  num_labels: 1
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 8
  dataroot: /projects/nlp_mgr-AUDIT/data/dataset/sxk199/flickr30k
  features_h5path1: /projects/nlp_mgr-AUDIT/data/dataset/sxk199/flickr30k/resnet101_faster_rcnn_genome_imgfeats/flickr30k_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: /projects/nlp_mgr-AUDIT/data/dataset/sxk199/flickr30k/annotations/train_ann.jsonl
  val_annotations_jsonpath: /projects/nlp_mgr-AUDIT/data/dataset/sxk199/flickr30k/annotations/valid_ann.jsonl
  max_seq_length: 30
  max_region_num: 36
  batch_size: 64
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 10
  format: 'lmdb'
TASK12:
  name: NLVR2
  type: VL-binary-classifier
  num_labels: 2
  loss: BCEWithLogitLoss
  process: nlvr
  task_id: 12
  dataroot: /projects/nlp_mgr-AUDIT/data/dataset/sxk199/nlvr2/annotations
  features_h5path1: /projects/nlp_mgr-AUDIT/data/dataset/sxk199/nlvr2/resnet101_faster_rcnn_genome_imgfeats/nlvr2_feat.lmdb
  _dataroot: /image/nlp-datasets/laura/data/nlvr2/annotations/
  _features_h5path1: /image/nlp-datasets/emanuele/data/nlvr2/resnet101_faster_rcnn_genome_imgfeats/volta/nlvr2_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: train
  val_split: dev
  lr: 0.00005
  num_epoch: 10
  format: 'lmdb'
TASK15:
  name: GQA
  type: VL-classifier-GQA
  num_labels: 1842
  loss: BCEWithLogitLoss
  process: normal
  task_id: 15
  dataroot: /projects/nlp_mgr-AUDIT/data/dataset/sxk199/gqa/annotations
  features_h5path1: /projects/nlp_mgr-AUDIT/data/dataset/sxk199/gqa/resnet101_faster_rcnn_genome_imgfeats/vg_gqa_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00001
  num_epoch: 10
  format: 'lmdb'