train_file: ['/projects/nlp/data/data/multimodal-gender-bias/data/ALBEF/mscoco/annotations/coco_train.hendrix.json']
train_neutral_file: ['/projects/nlp/data/data/multimodal-gender-bias/data/ALBEF/mscoco/gender-neutral/coco_train.hendrix.json']
laion_path: '' 

tokenizer_path: '/projects/nlp/data/pmh864/checkpoints/backbones/huggingface/bert-base-uncased'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0

image_size: 224
batch_size: 75
max_words: 30

queue_size: 57600
alpha: 0.4

# optimizer
weight_decay: 0.05
init_lr: 1e-4
min_lr: 1e-6
warmup_lr: 1e-6
lr_decay_rate: 0.9
max_epoch: 1
warmup_steps: 0.1

p_neutral_caption: 0.15
neutral_epochs: 1
